debugging

diff --git a/.github/workflows/changelog.yml b/.github/workflows/changelog.yml
--- a/.github/workflows/changelog.yml
+++ b/.github/workflows/changelog.yml
@@ -45,46 +45,43 @@ jobs:
       - name: Fetch main
         run: git fetch origin main:main
 
-      - name: git log
-        run: git log v9.0.0..main
+      - name: Update changelogs
+        run: ./scripts/changelog.sh
 
-      # - name: Update changelogs
-      #   run: ./scripts/changelog.sh
+      - name: Commit changes
+        run: |
+          git add .
+          git commit -m 'updated changelog'
 
-      # - name: Commit changes
-      #   run: |
-      #     git add .
-      #     git commit -m 'updated changelog'
+      - name: Push changes
+        id: push
+        continue-on-error: true
+        run: |
+          git push https://$GH_TOKEN@github.com/Stride-Labs/stride.git ${{ env.branch_name }}
+        env:
+          GH_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
 
-      # - name: Push changes
-      #   id: push
-      #   continue-on-error: true
-      #   run: |
-      #     git push https://$GH_TOKEN@github.com/Stride-Labs/stride.git ${{ env.branch_name }}
-      #   env:
-      #     GH_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
+      - name: Check Push Success
+        if: ${{ steps.push.outcome == 'failure' }}
+        run: |
+          echo "Push failed. The token might be expired or have insufficient permissions. Please check your token."
+          exit 1
 
-      # - name: Check Push Success
-      #   if: ${{ steps.push.outcome == 'failure' }}
-      #   run: |
-      #     echo "Push failed. The token might be expired or have insufficient permissions. Please check your token."
-      #     exit 1
+      - name: Fetch New Branch
+        run: |
+          git fetch --all
 
-      # - name: Fetch New Branch
-      #   run: |
-      #     git fetch --all
-
-      # - name: Create Pull Request
-      #   run: |
-      #     curl \
-      #     -X POST \
-      #     -H "Accept: application/vnd.github.v3+json" \
-      #     -H "Authorization: token ${{ secrets.GH_ACTIONS_PAT }}" \
-      #     https://api.github.com/repos/${{ github.repository }}/pulls \
-      #     -d '{
-      #     "title":"${{ env.NEW_MAJOR_VERSION }} Changelog",
-      #     "head":"${{ env.branch_name }}",
-      #     "base":"main",
-      #     "body":"This is an automatically generated pull request.\n\nPlease review and merge the changes. **Remember to split the On-Chain vs Off-Chain commits!**\n\n## Context\n\nUpdates changelog for ${{ env.NEW_MAJOR_VERSION }} release\n\n## Brief Changelog\n\n* Updates main changelog with on-chain and off-chain changes\n* Updates upgrade-specific changelog with on-chain changes only\n",
-      #     "maintainer_can_modify": true
-      #     }'
+      - name: Create Pull Request
+        run: |
+          curl \
+          -X POST \
+          -H "Accept: application/vnd.github.v3+json" \
+          -H "Authorization: token ${{ secrets.GH_ACTIONS_PAT }}" \
+          https://api.github.com/repos/${{ github.repository }}/pulls \
+          -d '{
+          "title":"${{ env.NEW_MAJOR_VERSION }} Changelog",
+          "head":"${{ env.branch_name }}",
+          "base":"main",
+          "body":"This is an automatically generated pull request.\n\nPlease review and merge the changes. **Remember to split the On-Chain vs Off-Chain commits!**\n\n## Context\n\nUpdates changelog for ${{ env.NEW_MAJOR_VERSION }} release\n\n## Brief Changelog\n\n* Updates main changelog with on-chain and off-chain changes\n* Updates upgrade-specific changelog with on-chain changes only\n",
+          "maintainer_can_modify": true
+          }'
